### ISSUE TITLE
Build resource vào file jar

### ISSUE THREAD

**Issue by ducquangkstn** [phuonglh/vn.vitk#10]
Hi thầy,
việc phải copy resource lên các máy khi chạy yarn-cluster khiến việc deploy khá khó khăn( người chạy ko có quyền trên các node slave, thêm mới node phải copy data ,...)
vậy có thể sửa theo hường build file resource vào jar như sau:
Trong thẻ poml.xml 
```xml
<build>
		<resources>
			<resource>
				<directory>models</directory>
				<targetPath>models</targetPath>
			</resource>			
		</resources>
</build>
```

như thế khi build ra file jar (cụ thể mở = trình giải nén) sẽ thấy thư mục dictionary trong file jar.
Khi muốn đọc 1 file trong resource thay vì dùng FileInputStream ta lấy stream như sau:
Tenclass.class.getResourceAsStream("/dictionary/test.txt")

**Comment by phuonglh** [comment]
Hi em,

Nếu gộp luôn từ điển và các models (gọi là các resources) vào trong file JAR cũng được nhưng như thế sẽ làm file JAR có kích thước lớn hơn. Không biết như thế có tiện không?

Em viết luôn bản pom.xml mới và sửa code nhé, rồi tạo pull request để mình merge vào là được. Thanks.

Phương
