### ISSUE TITLE
Constant variables should be uppercase

### ISSUE THREAD

**Issue by iamloivx** [phuonglh/vn.vitk#12]
There are many constant variables in some classes. They should be uppercase.
Follow [Code Conventions](http://www.oracle.com/technetwork/java/codeconventions-135099.html)

Example from `vn.vitk/src/main/java/vn/vitk/util/TokenNormalizer.java`
```
static Pattern number = Pattern.compile("^([\\+\\-\\.,]?([0-9]*)?[0-9]+([\\.,]\\d+)*[%°]?)$"); 
static Pattern punctuation = Pattern.compile("^([\\?!\\.:;,\\-\\+\\*\"'\\(\\)\\[\\]\\{\\}]+)$");
static Pattern email = Pattern.compile("^(\\w[\\-\\._\\w]*\\w@\\w[\\-\\._\\w]*\\w\\.\\w{2,3})$");
static Pattern date = Pattern.compile("^(\\d+[\\-\\./]\\d+([\\-\\./]\\d+)?)$|^(năm_)\\d+$");
static Pattern code = Pattern.compile("^(\\d+[\\-\\._/]?[\\w\\W\\-\\._/]+)$|^([\\w\\W\\-\\._/]+\\d+[\\-\\._/\\d]*[\\w\\W]*)$");
static Pattern website = Pattern.compile("^(\\w+\\.\\w+)(/\\w*)*$");
static Pattern xmlTag = Pattern.compile("^</?\\w+>$");
```

**Comment by phuonglh** [comment]
You are right if they have a "final" keyword. But here, they are used only as static variables, not as constant, for a better reading purpose. That's why I did not make them uppercase. Is there any problem with that personal choice?

**Comment by iamloivx** [comment]
I do not know "why do not you declare them as final variables?" Should we put them in their implementation functions if they do not need any references from others?

```
private static boolean isNumber(String token) {
    Pattern number = Pattern.compile("^([\\+\\-\\.,]?([0-9]*)?[0-9]+([\\.,]\\d+)*[%°]?)$");
    return number.matcher(token).matches();
}
```

Besides, using enumeration instead of string may be good for reading and maintenance.

```
public static String normalize(String token) {
	if (isNumber(token))
		return "1000";
	if (isPunctuation(token))
		return "PUNCT";
	if (isEmail(token))
		return "EMAIL";
	if (isDate(token))
		return "DATE";
	if (isCode(token))
		return "CODE";
	if (isWebsite(token))
		return "WEBSITE";
	if (isTag(token))
		return "XMLTAG";
	return token;
}
```

**Comment by phuonglh** [comment]
No. You should not put the patterns into functions. Otherwise, each time a function is called, the pattern is recompiled. That's an expensive operation which should be avoided.

In addition, I do not think that using enumeration is a better choice, mainly for the purpose of later development. Furthermore, the switch command works well with string literals in modern Java compilers.

I will close this "issue" here, if there will not any further discussion. Btw, I do not think that we have any problem here.
