### ISSUE TITLE
Support DongDu Pointwise Implementation

### ISSUE THREAD

**Issue by iamloivx** [phuonglh/vn.vitk#14]
DongDu mentioned that it can archive 98% at [Pointwise For Vietnamese Word Segmentation](https://github.com/rockkhuya/DongDu/blob/master/docs/Poinwise%20for%20Vietnamese%20Word%20Segmentaion.pdf). However, DongDu has not been maintained for 2 years (not answer, not accept pull-request, ...). Also, DongDu's implementation is not good enough (lot of problems with output when I run `predictor` tool on 100MB corpus)

Should we have an additional implementation for DongDu beside your hybrid approach?

Thanks and best regards,

**Comment by phuonglh** [comment]
Sorry, I'm too busy to implement other word segmentation approaches. Please go ahead by yourself if you are interested in these other works.
