### ISSUE TITLE
Improve Word Segmentation

### ISSUE THREAD

**Issue by iamloivx** [phuonglh/vn.vitk#15]
With the sentence `Với Thúy Kiều, đây lại là một lần cô dang dở`.
`Với Thúy Kiều` is tokenized as a word `Với_Thúy_Kiều`. Similarly, we have `Và, Bởi, ...`

How should we do to improve the word segmentation in these cases?

**Comment by phuonglh** [comment]
Yes, that's one of current segmentation problem. You should consider to update the last line of the regexp file:

https://github.com/phuonglh/vn.vitk/blob/master/dat/tok/regexp.txt
