### ISSUE TITLE
Hỏi về vntik

### ISSUE THREAD

**Issue by thanhtung0406** [phuonglh/vn.vitk#16]
Em chào thầy ạ, em có dùng thử phiên bản mới nhất và làm như hướng dẫn rồi import project vào IDE là eclipse và netbean nhưng em chạy thử mà chương trình vẫn báo lỗi ạ. Mong thầy giải đáp giúp em ạ. Em cảm ơn thầy

**Comment by phuonglh** [comment]
Hi. Please post the detailed error here. I cannot help you if I don't know what the error is.
