### ISSUE TITLE
where should I create /export/dat/... folder?

### ISSUE THREAD

**Issue by laynelee28** [phuonglh/vn.vitk#17]
hi! I meet the same problem with issue #13 
<Add option to run on single machine #13>
and you answered “ you need to do is to create the data folder /export/dat/ on that machine”，but，where should I create the file, under the C: disk or somewhere? can you give me more details?

**Comment by phuonglh** [comment]
Please have a look at my answer here. Thanks. https://github.com/phuonglh/vn.vitk/issues/13#issuecomment-313115795
