### ISSUE TITLE
lỗi khi load vn.vitk-3.0.jar

### ISSUE THREAD

**Issue by tiendungmta** [phuonglh/vn.vitk#20]
khi e chạy lệnh sau
~/spark/bin/spark-submit --class=vn.vitk.Vitk ~/vn.vitk/target/vn.vitk-3.0.jar -i <input file> -o <output-file>
thì lỗi java.lang.ClassNotFoundException: vn.vitk.Vitk ạ ????

**Comment by phuonglh** [comment]
Em đã dịch và đóng gói chưa? Trong thư mục target đã có tệp vn.vitk-3.0.jar chưa? Em nên đọc kĩ README, trong hướng dẫn không cần có tham số --class.

**Comment by tiendungmta** [comment]
trong thư mục có target có vn.vitk-3.0.jar rồi ạ. Nếu k dùng tham số --class thì nó sẽ báo
error: cannot load main class from JAR C:/vn.vitk/target/vn.vitk-3.0.jar with URI C. Please specify a class through --class

**Comment by phuonglh** [comment]
Có vẻ em đang chạy trên Windows. Dấu ~ chỉ thư mục chủ của người dùng trên Linux/Unix. Em kiểm tra xem có thực sự có tệp vn.vitk-3.0.jar trong đường dẫn 

C:/vn.vitk/target/vn.vitk-3.0.jar 

hay không? Thư mục chủ của Windows không phải là C:/

Nếu không, em cần chỉ định rõ đường dẫn tuyệt đối tới tệp jar này.

Nói chung, em không nên dùng Windows mà nên dùng Linux thì sẽ tránh được nhiều rắc rối với các phần mềm mã nguồn mở. Chí ít thì nên dùng Cygwin để giả lập Linux trong Windows.

**Comment by tiendungmta** [comment]
đúng rồi ạ. e dùng Window và sử dụng đường dấn C:/vn.vitk/target/vn.vitk-3.0.jar như thầy nói. và trong đường dẫn đó có thư mục vn.vitk-3.0.jar và xuất hiện lỗi này. do chương trình e viết trên C# nên e muốn viết trên window

**Comment by phuonglh** [comment]
Mình chưa bao giờ test thử chương trình này trên Windows, vì mình không dùng Windows từ khoảng năm 2002 tới giờ rồi nên mình không hỗ trợ em được nhé.

**Comment by tiendungmta** [comment]
em cảm ơn thầy !

**Comment by yldbk** [comment]
Chào bạn @tiendungmta 
Bình thường trên Win bạn chỉ cần chạy dòng lệnh ` spark-submit target/vn.vitk-3.0.jar` (`target/vn.vitk-3.0.jar` là đường dẫn tới file `vn.vitk-3.0.jar`), đường dẫn này có thể đặt cố định hay động.
Nếu `spark `báo lỗi thì có thể là lỗi của `spark `trên Win, Bạn kiểm tra đã set biến môi trường cho `spark `chưa, nếu chưa thì set  `SPARK_HOME`, `HADOOP_HOME `trỏ đường dẫn tới `spark-1.6.3-bin-hadoop2.6\bin`
Bạn cũng cần thêm công cụ gọi là `winutils` bạn xem hướng dẫn cài thêm ở đây
[https://github.com/steveloughran/winutils/tree/master/hadoop-2.6.0/bin](https://github.com/steveloughran/winutils/tree/master/hadoop-2.6.0/bin)

Thêm 1 vấn đề nữa là thư mục `/export/` không có, bạn có thể thử cách sau:
Clone vn.vitk của Thầy về, 
1. Đứng trong thư mục chính (chứa thư mục `src`, `dat`...) bạn tạo 1 thư mục là `export`, sau đó copy thư mục `dat `vao thư mục bạn vừa tạo.
2. Sửa đường dẫn trong code của thầy bằng cách tìm các từ` /export/` sửa lại thành đường dẫn của thư mục bạn vừa tạo ở 1.
3. Compile lại project bằng câu lệnh: `mvn compile package`
4. Chạy câu lệnh: `spark-submit target/vn.vitk-3.0.jar`

Bạn thử xem,

**Comment by TinyPoro** [comment]
@yldbk Chào bạn, sau khi làm theo hướng dẫn của bạn thì mình gặp tiếp lỗi này, không biết là do nguyên nhân gì ạ?
![image](https://user-images.githubusercontent.com/20787476/35485140-9d97eb22-048d-11e8-9b5c-975ac2f3f31d.png)
