### ISSUE TITLE
Thư viện có hỗ trợ output KQ ra XML không ạ ?

### ISSUE THREAD

**Issue by thelemontree10** [phuonglh/vn.vitk#22]
Em chào thầy,

So với bản 2011 thì em không biết các bản sau này thư viện của thầy có hỗ trợ output KQ ra file XML được không ạ ?

Em đọc readme thì không thấy đề cập gì.

Em cám ơn thầy ạ.

**Comment by phuonglh** [comment]
Không em nhé.
