### ISSUE TITLE
Tốc độ tokenize chậm

### ISSUE THREAD

**Issue by anhntn15** [phuonglh/vn.vitk#24]
Tốc độ tokenizer rất chậm đối với long text (vd: wiki chứa nhiều paragraph dài) hoặc các text chứa liên tiếp nhiều kí tự (vd: !!!)
Do không có option split_to_sentences(text) nên em không biết làm sao để giảm kích thước của text cần xử lý.

**Comment by phuonglh** [comment]
Bản cũ của vnTokenizer có tích hợp chức năng tách câu. Tuy nhiên bản mới thì không có. Em nên dùng một bộ tiền xử lí tách câu trước khi chạy tách từ. 

Dùng mô-đun tách câu tiếng Anh để áp dụng cho tiếng Việt cũng tốt, ví dụ dùng CoreNLP (https://stanfordnlp.github.io/CoreNLP/ssplit.html) hoặc dùng OpenNLP (https://opennlp.apache.org/docs/1.9.0/manual/opennlp.html#tools.sentdetect)

**Comment by anhntn15** [comment]
Dạ vâng, em cảm ơn thầy nhiều ạ.
