### ISSUE TITLE
Thắc mắc về đường đi ngắn nhất trong thuật toán

### ISSUE THREAD

**Issue by liv1n9** [phuonglh/vn.vitk#25]
Thầy ơi, em có chút thắc mắc muốn hỏi thầy ạ.

Em đọc theo tài liệu "a hybrid Approach to Word Segmentation of Vietnamese Texts" cùng blog của thầy trên FPT TechInsight, em đang hiểu đường đi ngắn nhất trên đồ thị xây dựng được là đường đi có số cung ít nhất, hay các cung có trọng số là 1. Nhưng lúc đọc code trong bản vitk-tok-5.2.jar thì em thấy các cạnh được gán trọng số là 1/(độ lớn khoảng cách giữa số hiệu 2 đỉnh). Việc gán này có ý nghĩa gì không ạ?

Em còn một thắc mắc nữa là theo tài liệu thì đường đi có xác suất lớn nhất sẽ được chọn, nhưng hình như trong vitk-tok-5.2.jar thì đường đi cuối cùng tìm được sẽ được chọn:

    List<LinkedList<Integer>> paths = graph.shortestPaths();
    if (paths.size() > 0) {
        LinkedList<Integer> selectedPath = (LinkedList)paths.get(paths.size() - 1);
        ...

Em chưa hiểu vì sao lại chọn như vậy ạ.

Mong được thầy hướng dẫn. Em xin cảm ơn ạ.

**Comment by phuonglh** [comment]
Chào em. Tài liệu mô tả thuật toán tách từ được gắn với bản cũ (vnTokenizer). Trong bản mới (vitk-tok) thì thầy không cài đặt việc chọn một đường theo xác suất mà chỉ chọn "bừa" một đường, đó là đường cuối cùng. Như thế cách chọn đó có thể dẫn tới phương án tách từ đúng hoặc sai. Người dùng thư viện này có thể gọi hàm liệt kê mọi đường đi ngắn nhất (ứng với mọi phương án tách từ) và xử lí tiếp sau.

Việc gán trọng số cho các cung (cạnh) có mục đích tìm đường đi ngắn nhất trên đồ thị dạng chuỗi tuyến tính. Ví dụ, nếu có hai cung, một cung đi từ đỉnh  1 tới đỉnh 5, một cung đi từ đỉnh 1 tới đỉnh 3 thì cung trước sẽ có trọng số bé hơn cung sau. Do đó, thuật toán tìm đường đi ngắn nhất sẽ ưu tiên dùng cung trước.

**Comment by liv1n9** [comment]
Em cảm ơn thầy ạ!

**Comment by liv1n9** [comment]
Em cảm ơn thầy ạ!
