### ISSUE TITLE
Tiếng Việt không dấu

### ISSUE THREAD

**Issue by vietthang207** [phuonglh/vn.vitk#3]
Em chào thầy ạ. Em hiện là sinh viên học computer science, em có quan tâm đến vn-nlp ạ.

Thầy ơi, cho em hỏi là nếu mình input tiếng việt không dấu, ví dụ "sinh vien vi pham quy che thi cu" thì output sẽ thế nào ạ.

**Comment by phuonglh** [comment]
Chào em,

Hiện tại Vitk không có chức năng xử lí tiếng Việt không dấu nhé. Trong ví
dụ trên thì sẽ ra các từ rời nhau không dấu thôi:

[sinh] [vien] [vi] [pham] [quy] [che] [thi] [cu]

Nếu em muốn tách được các từ không dấu thì cần bổ sung vào từ điển các từ
không dấu, ví dụ "sinh vien", "vi pham", "quy che", "thi cu".

Phương

2016-05-22 2:57 GMT+07:00 vietthang207 notifications@github.com:

**Comment by vietthang207** [comment]
Em cảm ơn thầy ạ. Theo em tìm hiểu thì hình như cũng chưa có nhiều solution cho bài toán thêm dấu phải không ạ.
