### ISSUE TITLE
How to specify output format Of tagger so that we can use the output for Dependency Parsing

### ISSUE THREAD

**Issue by cyberliem** [phuonglh/vn.vitk#5]
First of all, allow my humble self to express my gratitude and appreciation for your work. It seems to be one of the best tool for Natural Language Processing in Vietnamese. I stumbled upon the repository while walking my first steps on this area and find it really helpful. My goal is to build a sentiment Analysis tool/ Framework for Vietnamese. 

The tagger and segmentation seem to be in good working order. However it is really inconvenient when I want to use the ouput from tagger to run Dependency Parsing. I've opened the source code and took a look there with the hope that I can rewrite it so that instead of this format:

`{"sentence":"Đức đã ngã gục . Sau 90 phút với 65% kiểm_soát bóng vẫn đã không có bàn thắng , cho_dù đôi lúc đã rất gần với nó ","prediction":"Np R V A . E M N E N V N R R R V N V , C N N R R A E P "}`

It will represent this format, which is eligible for Dependency Parsing:

`{"sentence":"Đức/Np đã/R ngã/V gục/A . Sau/E 90/M phút/N với/E 65%/N kiểm_soát/V bóng/N vẫn/R đã/R không/R có/V bàn/N thắng/V , cho_dù/C đôi/N lúc/N đã/R rất/R gần/A với/E nó/P"}``

However, much of the code has been simplified, I found it's hard to write my own function there. May I ask if there's a way to specify output format? In the source code it seems to have three output format: JSON, PARQUET and TEXT (the TEXT seems to be the default). 

In addition to that, If it's possible, I hope to be able to contribute to the repository under your guidance. Thanks alot.

**Comment by phuonglh** [comment]
Dear Liem,

You're right. The current output format of the PoS tagging module is not very suitable as input to the DP module. I will fix that as soon as possible and I will notify you by email, probably in a few days.

In addition, I want to write a pipeline that chains the processing tools together, so that a user only needs to invoke one command to get the results of all integrated tools. If you have free time and are interested in that bit of work, you are welcome to contribute.

Regards,

Phuong

**Comment by cyberliem** [comment]
Dear Phuong,

Thanks for your promptly reply. As it happens I'm not familiar with programming Spark, I'll have to see into how the pipelining is done on this particular repository. I'll look into it and inform you before the end of this week.

**Comment by phuonglh** [comment]
Dear Liem,

The output problem you reported has been fixed. The default output format of part-of-speech tagging is TEXT and of the form "word1/tag1 ... wordN/tagN", each tagged sentence on a line, as your request. Check it out and give it a try. Thanks.

**Comment by cyberliem** [comment]
Thanks Phuong,

All is well now.. Great work.
